version: "3.5"
services:
  db:
    container_name: db
    image: postgres:15.3-bullseye
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: notes
    volumes:
      - db:/var/lib/postgresql/data
  pg-admin:
    image: dpage/pgadmin4:7.5
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=root
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    volumes:
      - admin:/var
  main:
    container_name: main
    build:
      context: .
    ports:
      - 4000:4000
    command: npm start
    depends_on:
      - db
    restart: always
    volumes:
      - main:/app
volumes:
  db:
    driver: local
  main:
    driver: local
  admin:
